// BED
import bed1 from "../assets/bed/bed1.jpg";
import bed2 from "../assets/bed/bed2.jpg";
import bed3 from "../assets/bed/bed3.jpg";
import bed4 from "../assets/bed/bed4.jpg";
import bed5 from "../assets/bed/bed5.jpg";
import bed6 from "../assets/bed/bed6.jpg";
import bed7 from "../assets/bed/bed7.jpg";
import bed8 from "../assets/bed/bed8.jpg";
import bed9 from "../assets/bed/bed9.jpg";
import bed10 from "../assets/bed/bed10.jpg";

// CAMERA
import cam1 from "../assets/camera/cam1.jpg";
import cam2 from "../assets/camera/cam2.jpg";
import cam3 from "../assets/camera/cam3.jpg";
import cam4 from "../assets/camera/cam4.jpg";
import cam5 from "../assets/camera/cam5.jpg";
import cam6 from "../assets/camera/cam6.jpg";
import cam7 from "../assets/camera/cam7.jpg";
import cam8 from "../assets/camera/cam8.jpg";
import cam9 from "../assets/camera/cam9.jpg";
import cam10 from "../assets/camera/cam10.jpg";

// FRIDGE
import fridge1 from "../assets/fridge/fridge1.jpg";
import fridge2 from "../assets/fridge/fridge2.jpg";
import fridge3 from "../assets/fridge/fridge3.jpg";
import fridge4 from "../assets/fridge/fridge4.jpg";
import fridge5 from "../assets/fridge/fridge5.jpg";
import fridge6 from "../assets/fridge/fridge6.jpg";
import fridge7 from "../assets/fridge/fridge7.jpg";
import fridge8 from "../assets/fridge/fridge8.jpg";
import fridge9 from "../assets/fridge/fridge9.jpg";
import fridge10 from "../assets/fridge/fridge10.jpg";

// SOFA
import sofa1 from "../assets/sofa/sofa1.jpg";
import sofa2 from "../assets/sofa/sofa2.jpg";
import sofa3 from "../assets/sofa/sofa3.jpg";
import sofa4 from "../assets/sofa/sofa4.jpg";
import sofa5 from "../assets/sofa/sofa5.jpg";
import sofa6 from "../assets/sofa/sofa6.jpg";
import sofa7 from "../assets/sofa/sofa7.jpg";
import sofa8 from "../assets/sofa/sofa8.jpg";
import sofa9 from "../assets/sofa/sofa9.jpg";
import sofa10 from "../assets/sofa/sofa10.jpg";

// ... imports remain the same

export const data = [
  // BEDS
  {
    id: 1,
    userId: "user1",
    productName: "Handcrafted Oakwood Queen Bed",
    itemType: "Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Like New",
    keywords: ["queen size", "wooden", "oak", "bedroom", "sleep", "home decor", "frame"],
    description: "Experience ultimate relaxation with this high-quality wooden bed frame designed for durability and style...",
    image: bed1,
    pricePerDay: 150,
    securityDeposit: 2000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 2,
    userId: "user2",
    productName: "Vintage Mahogany Single Bed",
    itemType: "Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    keywords: ["single bed", "mahogany", "vintage", "classic", "wood", "compact", "kids room"],
    description: "This premium bedroom bed offers a sophisticated aesthetic coupled with exceptional structural integrity...",
    image: bed2,
    pricePerDay: 140,
    securityDeposit: 1900,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 3,
    userId: "user3",
    productName: "Upholstered Velvet King Size Bed",
    itemType: "Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "New",
    keywords: ["king size", "velvet", "luxury", "upholstered", "royal", "soft headboard", "premium"],
    description: "Indulge in pure luxury with this magnificent king-size bed...",
    image: bed3,
    pricePerDay: 180,
    securityDeposit: 2300,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 4,
    userId: "user1",
    productName: "Industrial Metal Frame Bed",
    itemType: "Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    keywords: ["metal bed", "industrial", "iron", "strong", "minimalist", "guest room", "durable"],
    description: "A robust and durable bed built to withstand years of use...",
    image: bed4,
    pricePerDay: 130,
    securityDeposit: 1800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: true,
  },
  {
    id: 5,
    userId: "user2",
    productName: "Scandinavian Minimalist Platform Bed",
    itemType: "Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Like New",
    keywords: ["platform bed", "scandinavian", "low profile", "light wood", "modern", "aesthetic", "simple"],
    description: "This modern wooden bed features clean lines and a contemporary finish...",
    image: bed5,
    pricePerDay: 160,
    securityDeposit: 2100,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 6,
    userId: "user3",
    productName: "Classic Teakwood Slat Bed",
    itemType: "Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    keywords: ["teak", "slat bed", "wooden", "traditional", "natural", "bedroom", "sturdy"],
    description: "Embrace simplicity with this minimal style bed frame...",
    image: bed6,
    pricePerDay: 120,
    securityDeposit: 1700,
    totalStock: 4,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 7,
    userId: "user1",
    productName: "Modern Studio Twin Bed",
    itemType: "Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Used",
    keywords: ["twin bed", "studio", "compact", "cheap", "student", "small room", "practical"],
    description: "Looking for an affordable bed option? This pre-loved frame offers great value...",
    image: bed7,
    pricePerDay: 100,
    securityDeposit: 1500,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 8,
    userId: "user2",
    productName: "Colonial High-Poster Bed",
    itemType: "Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    keywords: ["poster bed", "colonial", "tall", "classic", "dark wood", "grand", "elegant"],
    description: "This durable bedroom bed is engineered for longevity and consistent support...",
    image: bed8,
    pricePerDay: 135,
    securityDeposit: 1800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 9,
    userId: "user3",
    productName: "Padded Headboard Double Bed",
    itemType: "Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Like New",
    keywords: ["double bed", "padded", "headboard", "cushioned", "modern", "suite", "comfy"],
    description: "A remarkably comfortable double bed that provides ample space for a restful sleep...",
    image: bed9,
    pricePerDay: 155,
    securityDeposit: 2000,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 10,
    userId: "user1",
    productName: "Sturdy Pine Wood Bed",
    itemType: "Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    keywords: ["pine wood", "sturdy", "heavy duty", "natural", "furniture", "home", "durable"],
    description: "This strong wooden bed combines traditional craftsmanship with modern durability...",
    image: bed10,
    pricePerDay: 145,
    securityDeposit: 1900,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },

  // CAMERAS
  {
    id: 11,
    userId: "user2",
    productName: "EOS Rebel T7 Professional Kit",
    itemType: "Camera",
    brand: "Canon",
    category: "Electronics",
    condition: "Like New",
    keywords: ["dslr", "canon", "photography", "professional", "lens", "camera kit", "shooting"],
    description: "Capture breathtaking images with this professional DSLR camera...",
    image: cam1,
    pricePerDay: 350,
    securityDeposit: 5000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 12,
    userId: "user3",
    productName: "EOS 5D Mark IV Body",
    itemType: "Camera",
    brand: "Canon",
    category: "Electronics",
    condition: "Good",
    keywords: ["full frame", "canon", "5d", "body only", "high res", "professional camera", "4k"],
    description: "This high-resolution camera delivers crisp and vibrant photos in any lighting condition...",
    image: cam2,
    pricePerDay: 320,
    securityDeposit: 4800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 13,
    userId: "user1",
    productName: "Alpha a7 III Mirrorless",
    itemType: "Camera",
    brand: "Sony",
    category: "Electronics",
    condition: "Like New",
    keywords: ["mirrorless", "sony", "alpha", "a7iii", "4k video", "content creation", "vlog"],
    description: "A compact mirrorless camera that packs incredible power into a portable frame...",
    image: cam3,
    pricePerDay: 380,
    securityDeposit: 5200,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 14,
    userId: "user2",
    productName: "Sony ZV-1 Vlogging Camera",
    itemType: "Camera",
    brand: "Sony",
    category: "Electronics",
    condition: "Good",
    keywords: ["vlog", "vlogging", "compact", "sony", "youtube", "streaming", "lightweight"],
    description: "This lightweight compact camera is perfect for capturing memories on the go...",
    image: cam4,
    pricePerDay: 300,
    securityDeposit: 4500,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 15,
    userId: "user3",
    productName: "Nikon D850 DSLR",
    itemType: "Camera",
    brand: "Nikon",
    category: "Electronics",
    condition: "Like New",
    keywords: ["nikon", "dslr", "d850", "high resolution", "outdoor", "professional", "landscape"],
    description: "An exceptional DSLR for photography lovers seeking depth and color accuracy...",
    image: cam5,
    pricePerDay: 360,
    securityDeposit: 5000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: true,
  },
  {
    id: 16,
    userId: "user1",
    productName: "Nikon Z6 Mirrorless System",
    itemType: "Camera",
    brand: "Nikon",
    category: "Electronics",
    condition: "Good",
    keywords: ["nikon", "mirrorless", "z6", "hd video", "digital camera", "hybrid", "autofocus"],
    description: "A reliable HD camera that excels in both photography and videography...",
    image: cam6,
    pricePerDay: 310,
    securityDeposit: 4600,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 17,
    userId: "user2",
    productName: "Canon EOS R6 Mark II",
    itemType: "Camera",
    brand: "Canon",
    category: "Electronics",
    condition: "Like New",
    keywords: ["canon", "r6", "mirrorless", "low light", "wedding photography", "fast", "pro"],
    description: "This advanced DSLR camera offers a massive sensor for incredible low-light performance...",
    image: cam7,
    pricePerDay: 370,
    securityDeposit: 5100,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 18,
    userId: "user3",
    productName: "Sony Alpha a6400",
    itemType: "Camera",
    brand: "Sony",
    category: "Electronics",
    condition: "Good",
    keywords: ["sony", "a6400", "mirrorless", "flip screen", "street photography", "compact", "eye tracking"],
    description: "A mirrorless compact camera that provides professional results in a pocket-sized package...",
    image: cam8,
    pricePerDay: 330,
    securityDeposit: 4800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 19,
    userId: "user1",
    productName: "Canon EOS 90D High-Speed",
    itemType: "Camera",
    brand: "Canon",
    category: "Electronics",
    condition: "Like New",
    keywords: ["canon", "90d", "sports photography", "action", "high speed", "optical", "fast shutter"],
    description: "High-performance photography DSLR designed for speed and precision...",
    image: cam9,
    pricePerDay: 360,
    securityDeposit: 5000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 20,
    userId: "user2",
    productName: "Nikon D7500 Enthusiast Camera",
    itemType: "Camera",
    brand: "Nikon",
    category: "Electronics",
    condition: "Good",
    keywords: ["nikon", "d7500", "enthusiast", "rugger", "studio", "dynamic range", "weather sealed"],
    description: "A professional-grade camera built for versatility and ruggedness...",
    image: cam10,
    pricePerDay: 340,
    securityDeposit: 4700,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },

  // FRIDGES
  {
    id: 21,
    userId: "user1",
    productName: "Samsung French Door Refrigerator",
    itemType: "Refrigerator",
    brand: "Samsung",
    category: "Appliances",
    condition: "Like New",
    keywords: ["french door", "refrigerator", "fridge", "double door", "stainless steel", "kitchen", "smart cooling"],
    description: "This double door refrigerator offers massive storage capacity and cutting-edge cooling technology...",
    image: fridge1,
    pricePerDay: 220,
    securityDeposit: 4000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 22,
    userId: "user2",
    productName: "LG Smart Inverter Fridge",
    itemType: "Refrigerator",
    brand: "LG",
    category: "Appliances",
    condition: "Good",
    keywords: ["lg", "inverter", "energy efficient", "fridge", "quiet", "apartment", "eco friendly"],
    description: "An energy-efficient fridge that reduces electricity bills while providing optimal performance...",
    image: fridge2,
    pricePerDay: 210,
    securityDeposit: 3800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 23,
    userId: "user3",
    productName: "Samsung Bespoke Side-by-Side",
    itemType: "Refrigerator",
    brand: "Samsung",
    category: "Appliances",
    condition: "Like New",
    keywords: ["side by side", "large fridge", "frost free", "led lighting", "bespoke", "samsung", "family size"],
    description: "This large refrigerator is designed for big households requiring plenty of space...",
    image: fridge3,
    pricePerDay: 230,
    securityDeposit: 4200,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 24,
    userId: "user1",
    productName: "LG InstaView Door-in-Door",
    itemType: "Refrigerator",
    brand: "LG",
    category: "Appliances",
    condition: "Good",
    keywords: ["instaview", "lg", "door in door", "glass door", "modern kitchen", "compact", "high performance"],
    description: "A stylish and modern fridge that complements any contemporary kitchen...",
    image: fridge4,
    pricePerDay: 200,
    securityDeposit: 3600,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 25,
    userId: "user2",
    productName: "Whirlpool Triple Door Refrigerator",
    itemType: "Refrigerator",
    brand: "Whirlpool",
    category: "Appliances",
    condition: "Like New",
    keywords: ["triple door", "whirlpool", "multi airflow", "spacious", "premium", "odor control", "fridge"],
    description: "This spacious fridge features multi-airflow technology to maintain even temperatures...",
    image: fridge5,
    pricePerDay: 240,
    securityDeposit: 4300,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 26,
    userId: "user3",
    productName: "Samsung Twin Cooling Plus",
    itemType: "Refrigerator",
    brand: "Samsung",
    category: "Appliances",
    condition: "Good",
    keywords: ["twin cooling", "humidity control", "freshness", "samsung", "smart fridge", "vegetable storage", "efficient"],
    description: "A reliable cooling refrigerator that excels in maintaining humidity levels...",
    image: fridge6,
    pricePerDay: 210,
    securityDeposit: 3900,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: true,
  },
  {
    id: 27,
    userId: "user1",
    productName: "LG Bottom Mount Refrigerator",
    itemType: "Refrigerator",
    brand: "LG",
    category: "Appliances",
    condition: "Like New",
    keywords: ["bottom mount", "freezer on bottom", "water dispenser", "lg", "double door", "luxury", "appliances"],
    description: "This premium double door fridge combines high-end aesthetics with practical features...",
    image: fridge7,
    pricePerDay: 220,
    securityDeposit: 4000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 28,
    userId: "user2",
    productName: "Whirlpool Protton Frost-Free",
    itemType: "Refrigerator",
    brand: "Whirlpool",
    category: "Appliances",
    condition: "Good",
    keywords: ["frost free", "whirlpool", "energy saving", "eco", "compact", "organized", "kitchen"],
    description: "An incredible energy-saving fridge designed for the environmentally conscious consumer...",
    image: fridge8,
    pricePerDay: 200,
    securityDeposit: 3500,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 29,
    userId: "user3",
    productName: "Samsung Digital Inverter Fridge",
    itemType: "Refrigerator",
    brand: "Samsung",
    category: "Appliances",
    condition: "Like New",
    keywords: ["digital inverter", "samsung", "smart controls", "fingerprint resistant", "modern", "led display", "tech"],
    description: "This modern refrigerator features a digital display and smart temperature controls...",
    image: fridge9,
    pricePerDay: 235,
    securityDeposit: 4200,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 30,
    userId: "user1",
    productName: "LG Compact Top Freezer",
    itemType: "Refrigerator",
    brand: "LG",
    category: "Appliances",
    condition: "Good",
    keywords: ["top freezer", "compact fridge", "lg", "reliable", "classic", "standard", "home appliances"],
    description: "A reliable fridge that delivers consistent cooling performance year after year...",
    image: fridge10,
    pricePerDay: 205,
    securityDeposit: 3600,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },

  // SOFAS
  {
    id: 31,
    userId: "user2",
    productName: "IKEA JÄTTEBO Sectional Sofa",
    itemType: "Sofa",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    keywords: ["sectional", "sofa", "ikea", "couch", "living room", "fabric", "l-shape", "modular"],
    description: "This comfortable living room sofa is upholstered in premium fabric...",
    image: sofa1,
    pricePerDay: 180,
    securityDeposit: 2500,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 32,
    userId: "user3",
    productName: "Urban Ladder Mid-Century Modern",
    itemType: "Sofa",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    keywords: ["mid-century", "modern", "sofa", "urban ladder", "office", "chic", "wooden frame"],
    description: "A stylish sofa that adds a contemporary flair to any home office or lounge...",
    image: sofa2,
    pricePerDay: 170,
    securityDeposit: 2400,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 33,
    userId: "user1",
    productName: "IKEA EKTORP 3-Seater Sofa",
    itemType: "Sofa",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    keywords: ["3 seater", "sofa", "ikea", "plush", "cozy", "apartment", "washable cover", "soft"],
    description: "This soft sofa is designed for those who value plush comfort above all else...",
    image: sofa3,
    pricePerDay: 190,
    securityDeposit: 2600,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 34,
    userId: "user2",
    productName: "Urban Ladder Tufted Leather Sofa",
    itemType: "Sofa",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    keywords: ["leather", "tufted", "sofa", "luxury", "urban ladder", "executive", "premium", "brown"],
    description: "A premium sofa that combines luxury with everyday functionality...",
    image: sofa4,
    pricePerDay: 175,
    securityDeposit: 2450,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 35,
    userId: "user3",
    productName: "IKEA KIVIK Loveseat",
    itemType: "Sofa",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    keywords: ["loveseat", "2 seater", "ikea", "small sofa", "minimalist", "grey", "compact"],
    description: "This modern sofa features a sleek profile and minimalist legs...",
    image: sofa5,
    pricePerDay: 185,
    securityDeposit: 2550,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: true,
  },
  {
    id: 36,
    userId: "user1",
    productName: "Urban Ladder Velvet Chesterfield",
    itemType: "Sofa",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    keywords: ["chesterfield", "velvet", "sofa", "classic", "urban ladder", "vintage", "elegant"],
    description: "A classic living room sofa that anchors your interior design with timeless grace...",
    image: sofa6,
    pricePerDay: 170,
    securityDeposit: 2400,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 37,
    userId: "user2",
    productName: "IKEA LANDSKRONA Luxury Suite",
    itemType: "Sofa",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    keywords: ["luxury suite", "sofa set", "ikea", "leather", "modern", "lounge", "complete set"],
    description: "This premium sofa set offers a coordinated look for your entire lounge area...",
    image: sofa7,
    pricePerDay: 200,
    securityDeposit: 2800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 38,
    userId: "user3",
    productName: "Urban Ladder L-Shaped Lounger",
    itemType: "Sofa",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    keywords: ["l-shape", "lounger", "corner sofa", "urban ladder", "ergonomic", "movie night", "big sofa"],
    description: "A comfortable sofa with a deep seat and ergonomic backrest...",
    image: sofa8,
    pricePerDay: 175,
    securityDeposit: 2500,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 39,
    userId: "user1",
    productName: "IKEA VIMLE Modular Sofa",
    itemType: "Sofa",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    keywords: ["modular", "ikea", "velvet", "customizable", "high end", "sofa", "luxury"],
    description: "This luxury sofa is the epitome of comfort and sophisticated design...",
    image: sofa9,
    pricePerDay: 210,
    securityDeposit: 2900,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 40,
    userId: "user2",
    productName: "Urban Ladder Solid Wood Settee",
    itemType: "Sofa",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    keywords: ["settee", "solid wood", "urban ladder", "traditional"],
    description: "A traditional wooden settee perfect for entryways or small living spaces...",
    image: sofa10,
    pricePerDay: 160,
    securityDeposit: 2200,
    totalStock: 1,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
];
