// BED
import bed1 from "../assets/bed/bed1.jpg";
import bed2 from "../assets/bed/bed2.jpg";
import bed3 from "../assets/bed/bed3.jpg";
import bed4 from "../assets/bed/bed4.jpg";
import bed5 from "../assets/bed/bed5.jpg";
import bed6 from "../assets/bed/bed6.jpg";
import bed7 from "../assets/bed/bed7.jpg";
import bed8 from "../assets/bed/bed8.jpg";
import bed9 from "../assets/bed/bed9.jpg";
import bed10 from "../assets/bed/bed10.jpg";

// CAMERA
import cam1 from "../assets/camera/cam1.jpg";
import cam2 from "../assets/camera/cam2.jpg";
import cam3 from "../assets/camera/cam3.jpg";
import cam4 from "../assets/camera/cam4.jpg";
import cam5 from "../assets/camera/cam5.jpg";
import cam6 from "../assets/camera/cam6.jpg";
import cam7 from "../assets/camera/cam7.jpg";
import cam8 from "../assets/camera/cam8.jpg";
import cam9 from "../assets/camera/cam9.jpg";
import cam10 from "../assets/camera/cam10.jpg";

// FRIDGE
import fridge1 from "../assets/fridge/fridge1.jpg";
import fridge2 from "../assets/fridge/fridge2.jpg";
import fridge3 from "../assets/fridge/fridge3.jpg";
import fridge4 from "../assets/fridge/fridge4.jpg";
import fridge5 from "../assets/fridge/fridge5.jpg";
import fridge6 from "../assets/fridge/fridge6.jpg";
import fridge7 from "../assets/fridge/fridge7.jpg";
import fridge8 from "../assets/fridge/fridge8.jpg";
import fridge9 from "../assets/fridge/fridge9.jpg";
import fridge10 from "../assets/fridge/fridge10.jpg";

// SOFA
import sofa1 from "../assets/sofa/sofa1.jpg";
import sofa2 from "../assets/sofa/sofa2.jpg";
import sofa3 from "../assets/sofa/sofa3.jpg";
import sofa4 from "../assets/sofa/sofa4.jpg";
import sofa5 from "../assets/sofa/sofa5.jpg";
import sofa6 from "../assets/sofa/sofa6.jpg";
import sofa7 from "../assets/sofa/sofa7.jpg";
import sofa8 from "../assets/sofa/sofa8.jpg";
import sofa9 from "../assets/sofa/sofa9.jpg";
import sofa10 from "../assets/sofa/sofa10.jpg";

export const data = [
  // BEDS
  {
    id: 1,
    userId: "user1",
    productName: "Handcrafted Oakwood Queen Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Like New",
    description:
      "Experience ultimate relaxation with this high-quality wooden bed frame designed for durability and style. Its ergonomic support ensures a peaceful night's sleep while perfectly complementing any modern or traditional bedroom decor.",
    image: bed1,
    pricePerDay: 150,
    securityDeposit: 2000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 2,
    userId: "user2",
    productName: "Vintage Mahogany Single Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    description:
      "This premium bedroom bed offers a sophisticated aesthetic coupled with exceptional structural integrity. Ideal for long-term use, it provides a stable foundation and a touch of elegance to your home environment.",
    image: bed2,
    pricePerDay: 140,
    securityDeposit: 1900,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 3,
    userId: "user3",
    productName: "Upholstered Velvet King Size Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "New",
    description:
      "Indulge in pure luxury with this magnificent king-size bed. Featuring plush upholstery and a grand silhouette, it transforms your sleeping area into a five-star suite experience while offering maximum comfort daily.",
    image: bed3,
    pricePerDay: 180,
    securityDeposit: 2300,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 4,
    userId: "user1",
    productName: "Industrial Metal Frame Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    description:
      "A robust and durable bed built to withstand years of use. This practical design focuses on strength and simplicity, making it an excellent choice for guest rooms or growing busy households.",
    image: bed4,
    pricePerDay: 130,
    securityDeposit: 1800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: true,
  },
  {
    id: 5,
    userId: "user2",
    productName: "Scandinavian Minimalist Platform Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Like New",
    description:
      "This modern wooden bed features clean lines and a contemporary finish. Crafted from sustainable materials, it provides a sturdy yet stylish base that fits seamlessly into any minimalist living space today.",
    image: bed5,
    pricePerDay: 160,
    securityDeposit: 2100,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 6,
    userId: "user3",
    productName: "Classic Teakwood Slat Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    description:
      "Embrace simplicity with this minimal style bed frame. Its understated design highlights natural textures, offering a serene atmosphere for your bedroom while maintaining a high standard of comfort and reliability.",
    image: bed6,
    pricePerDay: 120,
    securityDeposit: 1700,
    totalStock: 4,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 7,
    userId: "user1",
    productName: "Modern Studio Twin Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Used",
    description:
      "Looking for an affordable bed option? This pre-loved frame offers great value without compromising on structural safety. It is a cost-effective solution for students or temporary housing needs right now.",
    image: bed7,
    pricePerDay: 100,
    securityDeposit: 1500,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 8,
    userId: "user2",
    productName: "Colonial High-Poster Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    description:
      "This durable bedroom bed is engineered for longevity and consistent support. Its classic aesthetic ensures it never goes out of style, providing a dependable and cozy sanctuary for your nightly rest.",
    image: bed8,
    pricePerDay: 135,
    securityDeposit: 1800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 9,
    userId: "user3",
    productName: "Padded Headboard Double Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Like New",
    description:
      "A remarkably comfortable double bed that provides ample space for a restful sleep. The sleek finish and sturdy legs make it a beautiful centerpiece for any master or guest bedroom suite.",
    image: bed9,
    pricePerDay: 155,
    securityDeposit: 2000,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 10,
    userId: "user1",
    productName: "Sturdy Pine Wood Bed",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    description:
      "This strong wooden bed combines traditional craftsmanship with modern durability. Its heavy-duty construction guarantees years of dependable service, making it a wise investment for anyone seeking quality furniture at home.",
    image: bed10,
    pricePerDay: 145,
    securityDeposit: 1900,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },

  // CAMERAS
  {
    id: 11,
    userId: "user2",
    productName: "EOS Rebel T7 Professional Kit",
    brand: "Canon",
    category: "Electronics",
    condition: "Like New",
    description:
      "Capture breathtaking images with this professional DSLR camera. Featuring advanced sensors and fast autofocus, it is perfect for both portraits and landscapes, ensuring every detail is preserved with stunning visual clarity.",
    image: cam1,
    pricePerDay: 350,
    securityDeposit: 5000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 12,
    userId: "user3",
    productName: "EOS 5D Mark IV Body",
    brand: "Canon",
    category: "Electronics",
    condition: "Good",
    description:
      "This high-resolution camera delivers crisp and vibrant photos in any lighting condition. Its versatile lens compatibility and user-friendly interface make it a top choice for aspiring photographers and seasoned hobbyists alike.",
    image: cam2,
    pricePerDay: 320,
    securityDeposit: 4800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 13,
    userId: "user1",
    productName: "Alpha a7 III Mirrorless",
    brand: "Sony",
    category: "Electronics",
    condition: "Like New",
    description:
      "A compact mirrorless camera that packs incredible power into a portable frame. With lightning-fast processing and 4K video capabilities, it is the ultimate tool for content creators and travel enthusiasts everywhere.",
    image: cam3,
    pricePerDay: 380,
    securityDeposit: 5200,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 14,
    userId: "user2",
    productName: "Sony ZV-1 Vlogging Camera",
    brand: "Sony",
    category: "Electronics",
    condition: "Good",
    description:
      "This lightweight compact camera is perfect for capturing memories on the go. Its intuitive controls and impressive zoom allow you to get close to the action without carrying heavy gear around.",
    image: cam4,
    pricePerDay: 300,
    securityDeposit: 4500,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 15,
    userId: "user3",
    productName: "Nikon D850 DSLR",
    brand: "Nikon",
    category: "Electronics",
    condition: "Like New",
    description:
      "An exceptional DSLR for photography lovers seeking depth and color accuracy. This model features a rugged body and long battery life, making it ideal for outdoor adventures and long shooting sessions.",
    image: cam5,
    pricePerDay: 360,
    securityDeposit: 5000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: true,
  },
  {
    id: 16,
    userId: "user1",
    productName: "Nikon Z6 Mirrorless System",
    brand: "Nikon",
    category: "Electronics",
    condition: "Good",
    description:
      "A reliable HD camera that excels in both photography and videography. Its intelligent scene detection helps beginners take professional-looking shots while providing manual controls for more advanced and creative users today.",
    image: cam6,
    pricePerDay: 310,
    securityDeposit: 4600,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 17,
    userId: "user2",
    productName: "Canon EOS R6 Mark II",
    brand: "Canon",
    category: "Electronics",
    condition: "Like New",
    description:
      "This advanced DSLR camera offers a massive sensor for incredible low-light performance. Ideal for wedding photography or commercial work, it ensures every frame is sharp, clear, and full of rich detail.",
    image: cam7,
    pricePerDay: 370,
    securityDeposit: 5100,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 18,
    userId: "user3",
    productName: "Sony Alpha a6400",
    brand: "Sony",
    category: "Electronics",
    condition: "Good",
    description:
      "A mirrorless compact camera that provides professional results in a pocket-sized package. Perfect for vlogging or street photography, it features a flip screen and excellent eye-tracking technology for perfect portraits always.",
    image: cam8,
    pricePerDay: 330,
    securityDeposit: 4800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 19,
    userId: "user1",
    productName: "Canon EOS 90D High-Speed",
    brand: "Canon",
    category: "Electronics",
    condition: "Like New",
    description:
      "High-performance photography DSLR designed for speed and precision. Capture fast-moving subjects with ease thanks to its high frame rate and superior optical viewfinder, making it a favorite for sports photography enthusiasts.",
    image: cam9,
    pricePerDay: 360,
    securityDeposit: 5000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 20,
    userId: "user2",
    productName: "Nikon D7500 Enthusiast Camera",
    brand: "Nikon",
    category: "Electronics",
    condition: "Good",
    description:
      "A professional-grade camera built for versatility and ruggedness. Whether shooting in the studio or out in the elements, this device provides consistent quality and impressive dynamic range for every single shot.",
    image: cam10,
    pricePerDay: 340,
    securityDeposit: 4700,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },

  // FRIDGES
  {
    id: 21,
    userId: "user1",
    productName: "Samsung French Door Refrigerator",
    brand: "Samsung",
    category: "Appliances",
    condition: "Like New",
    description:
      "This double door refrigerator offers massive storage capacity and cutting-edge cooling technology. Keep your groceries fresher for longer with its independent temperature zones and sleek, modern stainless steel exterior finish today.",
    image: fridge1,
    pricePerDay: 220,
    securityDeposit: 4000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 22,
    userId: "user2",
    productName: "LG Smart Inverter Fridge",
    brand: "LG",
    category: "Appliances",
    condition: "Good",
    description:
      "An energy-efficient fridge that reduces electricity bills while providing optimal performance. Its quiet operation and adjustable shelving make it a perfect fit for modern apartments and families seeking sustainable appliance solutions.",
    image: fridge2,
    pricePerDay: 210,
    securityDeposit: 3800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 23,
    userId: "user3",
    productName: "Samsung Bespoke Side-by-Side",
    brand: "Samsung",
    category: "Appliances",
    condition: "Like New",
    description:
      "This large refrigerator is designed for big households requiring plenty of space. It features advanced frost-free technology and elegant LED lighting, ensuring your food stays organized and visible at all times.",
    image: fridge3,
    pricePerDay: 230,
    securityDeposit: 4200,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 24,
    userId: "user1",
    productName: "LG InstaView Door-in-Door",
    brand: "LG",
    category: "Appliances",
    condition: "Good",
    description:
      "A stylish and modern fridge that complements any contemporary kitchen. With its slim profile and high-performance compressor, it delivers consistent cooling and plenty of storage without taking up excessive floor space.",
    image: fridge4,
    pricePerDay: 200,
    securityDeposit: 3600,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 25,
    userId: "user2",
    productName: "Whirlpool Triple Door Refrigerator",
    brand: "Whirlpool",
    category: "Appliances",
    condition: "Like New",
    description:
      "This spacious fridge features multi-airflow technology to maintain even temperatures throughout the cabinet. Its durable build and sleek handles provide a premium feel while keeping your perishable items in perfect condition.",
    image: fridge5,
    pricePerDay: 240,
    securityDeposit: 4300,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 26,
    userId: "user3",
    productName: "Samsung Twin Cooling Plus",
    brand: "Samsung",
    category: "Appliances",
    condition: "Good",
    description:
      "A reliable cooling refrigerator that excels in maintaining humidity levels for fruits and vegetables. Its smart sensors monitor usage patterns to optimize power consumption while ensuring everything remains perfectly chilled inside.",
    image: fridge6,
    pricePerDay: 210,
    securityDeposit: 3900,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: true,
  },
  {
    id: 27,
    userId: "user1",
    productName: "LG Bottom Mount Refrigerator",
    brand: "LG",
    category: "Appliances",
    condition: "Like New",
    description:
      "This premium double door fridge combines high-end aesthetics with practical features. Enjoy built-in water dispensing and a large freezer section, making it the ideal appliance for entertaining guests or large families.",
    image: fridge7,
    pricePerDay: 220,
    securityDeposit: 4000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 28,
    userId: "user2",
    productName: "Whirlpool Protton Frost-Free",
    brand: "Whirlpool",
    category: "Appliances",
    condition: "Good",
    description:
      "An incredible energy-saving fridge designed for the environmentally conscious consumer. It offers excellent cooling retention during power outages and plenty of door bins to keep your bottles and condiments neatly organized.",
    image: fridge8,
    pricePerDay: 200,
    securityDeposit: 3500,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 29,
    userId: "user3",
    productName: "Samsung Digital Inverter Fridge",
    brand: "Samsung",
    category: "Appliances",
    condition: "Like New",
    description:
      "This modern refrigerator features a digital display and smart temperature controls. Its sleek design and fingerprint-resistant finish ensure your kitchen looks tidy while providing the latest in food preservation technology today.",
    image: fridge9,
    pricePerDay: 235,
    securityDeposit: 4200,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 30,
    userId: "user1",
    productName: "LG Compact Top Freezer",
    brand: "LG",
    category: "Appliances",
    condition: "Good",
    description:
      "A reliable fridge that delivers consistent cooling performance year after year. Its classic design and sturdy shelves make it a practical choice for any home, offering dependable storage for all groceries.",
    image: fridge10,
    pricePerDay: 205,
    securityDeposit: 3600,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },

  // SOFAS
  {
    id: 31,
    userId: "user2",
    productName: "IKEA JÄTTEBO Sectional Sofa",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    description:
      "This comfortable living room sofa is upholstered in premium fabric for a soft touch and elegant look. Its deep cushions provide exceptional support, making it the perfect spot for family relaxation.",
    image: sofa1,
    pricePerDay: 180,
    securityDeposit: 2500,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 32,
    userId: "user3",
    productName: "Urban Ladder Mid-Century Modern",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    description:
      "A stylish sofa that adds a contemporary flair to any home office or lounge. Featuring a sturdy wooden frame and chic upholstery, it offers both aesthetic appeal and long-lasting seated comfort.",
    image: sofa2,
    pricePerDay: 170,
    securityDeposit: 2400,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 33,
    userId: "user1",
    productName: "IKEA EKTORP 3-Seater Sofa",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    description:
      "This soft sofa is designed for those who value plush comfort above all else. Its oversized pillows and durable fabric make it an inviting addition to any cozy apartment living room.",
    image: sofa3,
    pricePerDay: 190,
    securityDeposit: 2600,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 34,
    userId: "user2",
    productName: "Urban Ladder Tufted Leather Sofa",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    description:
      "A premium sofa that combines luxury with everyday functionality. Its high-density foam cushions maintain their shape over time, ensuring a supportive and comfortable seating experience for your guests and family alike.",
    image: sofa4,
    pricePerDay: 175,
    securityDeposit: 2450,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 35,
    userId: "user3",
    productName: "IKEA KIVIK Loveseat",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    description:
      "This modern sofa features a sleek profile and minimalist legs for a clean aesthetic. It is a versatile piece that fits perfectly in smaller spaces without sacrificing any style or comfort.",
    image: sofa5,
    pricePerDay: 185,
    securityDeposit: 2550,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: true,
  },
  {
    id: 36,
    userId: "user1",
    productName: "Urban Ladder Velvet Chesterfield",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    description:
      "A classic living room sofa that anchors your interior design with timeless grace. Its neutral tones and durable construction make it an ideal choice for busy households with children or pets.",
    image: sofa6,
    pricePerDay: 170,
    securityDeposit: 2400,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 37,
    userId: "user2",
    productName: "IKEA LANDSKRONA Luxury Suite",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    description:
      "This premium sofa set offers a coordinated look for your entire lounge area. Built with high-quality materials, it provides a luxurious seating experience while being incredibly easy to clean and maintain.",
    image: sofa7,
    pricePerDay: 200,
    securityDeposit: 2800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 38,
    userId: "user3",
    productName: "Urban Ladder L-Shaped Lounger",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    description:
      "A comfortable sofa with a deep seat and ergonomic backrest. Perfect for movie nights or reading, its sturdy frame ensures that it remains a reliable part of your home for years.",
    image: sofa8,
    pricePerDay: 175,
    securityDeposit: 2500,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 39,
    userId: "user1",
    productName: "IKEA VIMLE Modular Sofa",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    description:
      "This luxury sofa is the epitome of comfort and sophisticated design. With hand-stitched details and velvet-feel fabric, it makes a bold statement in any high-end living space or executive lounge area.",
    image: sofa9,
    pricePerDay: 210,
    securityDeposit: 2900,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
    isOutOfStock: false,
  },
  {
    id: 40,
    userId: "user2",
    productName: "Urban Ladder Solid Wood Settee",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    description:
      "A classic sofa featuring traditional lines and heavy-duty upholstery. This piece is built to endure daily use while providing a warm and welcoming atmosphere for all your friends and family members.",
    image: sofa10,
    pricePerDay: 180,
    securityDeposit: 2600,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
    isOutOfStock: false,
  },
];
