export const searchSuggestions = [
  // Categories
  "Furniture",
  "Electronics",
  "Appliances",

  // Brands
  "SleepWell",
  "Canon",
  "Sony",
  "Nikon",
  "Samsung",
  "LG",
  "Whirlpool",
  "IKEA",
  "Urban Ladder",

  // Product Types & Styles
  "Queen Bed",
  "King Size Bed",
  "Single Bed",
  "Twin Bed",
  "Platform Bed",
  "DSLR Camera",
  "Mirrorless Camera",
  "Vlogging Camera",
  "Refrigerator",
  "French Door Fridge",
  "Side-by-Side Fridge",
  "Sectional Sofa",
  "L-Shaped Sofa",
  "Leather Sofa",
  "Chesterfield",
  "Loveseat",

  // Features & Materials
  "Oakwood",
  "Mahogany",
  "Teakwood",
  "Velvet",
  "Metal Frame",
  "4K Video",
  "Full Frame",
  "Low Light",
  "Stainless Steel",
  "Inverter",
  "Frost-Free",
  "Minimalist",
  "Scandinavian",
  "Industrial",
  "Vintage",
  "Modern",
];
